GET http://localhost:3000/items

###

GET http://localhost:3000/items/61b7087972831b220e718127

###

POST http://localhost:3000/items
Content-Type: application/json

{
  "name": "dummy"
}

###

DELETE  http://localhost:3000/items/61b7087972831b220e718127

###

PATCH  http://localhost:3000/items/61b70cbe6127cd78d9a8fdd5
Content-Type: application/json

{
  "name": "a new name"
}

